youtube:
  api:
    accesstoken: ${youtube.api.accesstoken.value}
line:
  bot:
    channel-token: ${line.channel.token.value}
    channel-secret: ${line.channel.secret.value}
    handler:
      path: /callback
